#!/usr/bin/env node
const fs = require('fs')
const path = require('path')

const pagesDir = path.join(__dirname, '..', 'pages')
const indexPath = path.join(__dirname, '..', 'index.qmd')

function parseFrontMatter(content) {
  if (!content.startsWith('---')) return {}
  const end = content.indexOf('\n---', 3)
  if (end === -1) return {}
  const yaml = content.slice(3, end + 1)
  const lines = yaml.split(/\r?\n/)
  const data = {}
  for (const line of lines) {
    const m = line.match(/^\s*([A-Za-z0-9_-]+):\s*(.*)$/)
    if (m) {
      const k = m[1]
      let v = m[2]
      // strip quotes
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1)
      }
      data[k] = v
    }
  }
  return data
}

function readPages() {
  const files = fs.readdirSync(pagesDir).filter(f => f.endsWith('.qmd'))
  const items = []
  for (const f of files) {
    const p = path.join(pagesDir, f)
    const content = fs.readFileSync(p, 'utf8')
    const fm = parseFrontMatter(content)
    const stats = fs.statSync(p)
    const date = fm.date || stats.mtime.toISOString()
    const title = fm.title || path.basename(f, '.qmd')
    const href = `pages/${path.basename(f, '.qmd')}.html`
    items.push({ title, href, date, file: f })
  }
  return items
}

function groupByYear(items) {
  const map = {}
  for (const it of items) {
    const year = new Date(it.date).getFullYear() || 'Unknown'
    if (!map[year]) map[year] = []
    map[year].push(it)
  }
  // sort years desc
  const years = Object.keys(map).sort((a,b)=>b-a)
  for (const y of years) {
    map[y].sort((a,b)=> new Date(b.date) - new Date(a.date))
  }
  return { years, map }
}

function buildIndex(years, map) {
  const lines = []
  lines.push('---')
  lines.push('title: "Code notebook"')
  lines.push('format: html')
  lines.push('---')
  lines.push('')
  lines.push('## Notebook Index')
  lines.push('')
  lines.push('This is the landing index for your notebook. Edit pages locally (in `pages/`) and publish — each page will be linked below after rendering.')
  lines.push('')
  for (const y of years) {
    lines.push(`### ${y}`)
    lines.push('')
    for (const it of map[y]) {
      const d = new Date(it.date).toISOString().slice(0,10)
      lines.push(`- [${it.title}](${it.href}) — ${d}`)
    }
    lines.push('')
  }
  lines.push('<!-- Generated by scripts/generate-index.js -->')
  lines.push('')
  return lines.join('\n')
}

function main(){
  const items = readPages()
  const { years, map } = groupByYear(items)
  const content = buildIndex(years, map)
  fs.writeFileSync(indexPath, content, 'utf8')
  console.log('Updated index.qmd with', items.length, 'pages across', years.length, 'years')
}

main()
